In [1]:
from google.colab import drive
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
drive_base_dir = '/content/drive/MyDrive/project/autoscout'

In [5]:
drive_data_dir = drive_base_dir+'/data'
drive_model_dir = drive_base_dir+'/model'
drive_plot_dir = drive_base_dir+'/plot'
drive_script_dir = drive_base_dir+'/script'

In [6]:
!jupyter nbconvert --to script '{drive_base_dir}/data_encoding.ipynb'
!mv '{drive_base_dir}/data_encoding.py' '{drive_script_dir}'

[NbConvertApp] Converting notebook /content/drive/MyDrive/project/autoscout/data_encoding.ipynb to script
[NbConvertApp] Writing 2739 bytes to /content/drive/MyDrive/project/autoscout/data_encoding.py

### Dataset import

In [7]:
df = pd.read_csv(drive_data_dir+'/data_to_encode.csv')

In [8]:
df.head()

,make_model,body_type,vat,prev_owner,type,inspection_new,body_color,paint_type,upholstery_texture,upholstery_color,gearing_type,fuel,co2_emission,emission_class,emission_label,drive_chain,consumption_comb,consumption_city,consumption_country,country_version,entertainment_media,safety_security,comfort_convenience,extras,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears,age
0,Audi A1,Sedans,VAT deductible,2.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Catalytic Converter,Voice Control",15770,56013.0,66.0,1422.0,0.0,1220.0,5.0,5.0,3.0,5.0,3.0
1,Audi A1,Sedans,Price negotiable,1.0,Used,No,Red,Metallic,Cloth,Grey,Automatic,Gasoline,129.0,Euro 6,4.0,Front,5.6,7.1,4.7,Germany,"Bluetooth,Hands-free equipment,On-board comput...","ABS,Central door lock,Central door lock with r...","Air conditioning,Automatic climate control,Hil...","Alloy wheels,Sport seats,Sport suspension,Voic...",14500,80000.0,141.0,1798.0,0.0,1255.0,3.0,4.0,4.0,7.0,2.0
2,Audi A1,Sedans,VAT deductible,1.0,Used,No,Black,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.4,3.4,Germany,"MP3,On-board computer","ABS,Central door lock,Daytime running lights,D...","Air conditioning,Cruise control,Electrical sid...","Alloy wheels,Voice Control",14640,83450.0,85.0,1598.0,0.0,1195.0,4.0,4.0,3.0,5.0,3.0
3,Audi A1,Sedans,Missing,1.0,Used,No,Brown,Metallic,Cloth,Black,Automatic,Diesel,99.0,Euro 6,4.0,Front,3.8,4.3,3.5,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Alarm system,Central door lock with remote...","Air suspension,Armrest,Auxiliary heating,Elect...","Alloy wheels,Sport seats,Voice Control",14500,73000.0,66.0,1422.0,0.0,1195.0,3.0,4.0,3.0,6.0,3.0
4,Audi A1,Sedans,Missing,1.0,Used,Yes,Black,Metallic,Cloth,Black,Automatic,Diesel,109.0,Euro 6,4.0,Front,4.1,4.6,3.8,Germany,"Bluetooth,CD player,Hands-free equipment,MP3,O...","ABS,Central door lock,Driver-side airbag,Elect...","Air conditioning,Armrest,Automatic climate con...","Alloy wheels,Sport package,Sport suspension,Vo...",16790,16200.0,66.0,1422.0,0.0,1195.0,5.0,5.0,3.0,5.0,3.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15915 entries, 0 to 15914
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   make_model           15915 non-null  object
 1   body_type            15915 non-null  object
 2   vat                  15915 non-null  object
 3   prev_owner           15915 non-null  float64
 4   type                 15915 non-null  object
 5   inspection_new       15915 non-null  object
 6   body_color           15915 non-null  object
 7   paint_type           15915 non-null  object
 8   upholstery_texture   15915 non-null  object
 9   upholstery_color     15915 non-null  object
 10  gearing_type         15915 non-null  object
 11  fuel                 15915 non-null  object
 12  co2_emission         15915 non-null  float64
 13  emission_class       15915 non-null  object
 14  emission_label       15915 non-null  float64
 15  drive_chain          15915 non-null  object
 16  consumption_comb     15915 non-null  float64
 17  consumption_city     15915 non-null  float64
 18  consumption_country  15915 non-null  float64
 19  country_version      15915 non-null  object
 20  entertainment_media  15915 non-null  object
 21  safety_security      15915 non-null  object
 22  comfort_convenience  15915 non-null  object
 23  extras               15915 non-null  object
 24  price                15915 non-null  int64
 25  km                   15915 non-null  float64
 26  hp                   15915 non-null  float64
 27  displacement         15915 non-null  float64
 28  warranty             15915 non-null  float64
 29  weight               15915 non-null  float64
 30  nr_of_doors          15915 non-null  float64
 31  nr_of_seats          15915 non-null  float64
 32  cylinders            15915 non-null  float64
 33  gears                15915 non-null  float64
 34  age                  15915 non-null  float64
dtypes: float64(16), int64(1), object(18)
memory usage: 4.2+ MB

In [10]:
df.describe(include=np.number).T

,count,mean,std,min,25%,50%,75%,max
prev_owner,15915.0,0.948916,0.392645,0.0,1.0,1.0,1.0,4.0
co2_emission,15915.0,117.269244,17.642774,0.0,104.0,117.0,126.0,253.0
emission_label,15915.0,3.925039,0.470011,1.0,4.0,4.0,4.0,5.0
consumption_comb,15915.0,4.833073,0.927657,0.0,4.0,4.8,5.4,13.8
consumption_city,15915.0,5.896993,1.393790,0.0,4.6,5.8,6.9,19.9
consumption_country,15915.0,4.199083,0.721686,0.0,3.7,4.2,4.5,10.3
price,15915.0,18024.380584,7381.679318,4950.0,12850.0,16900.0,21900.0,74600.0
km,15915.0,31979.579196,37073.900998,0.0,2000.0,20416.0,46928.0,317000.0
hp,15915.0,88.491298,26.664578,40.0,66.0,85.0,103.0,294.0
displacement,15915.0,1428.302890,275.898517,890.0,1229.0,1461.0,1598.0,2967.0
warranty,15915.0,6.686334,13.332171,0.0,0.0,0.0,12.0,72.0
weight,15915.0,1345.787716,202.491489,840.0,1180.0,1308.0,1472.0,2471.0
nr_of_doors,15915.0,4.660697,0.642127,1.0,4.0,5.0,5.0,7.0
nr_of_seats,15915.0,4.952246,0.476658,2.0,5.0,5.0,5.0,7.0
cylinders,15915.0,3.815771,0.396656,1.0,4.0,4.0,4.0,8.0
gears,15915.0,5.810870,0.697701,1.0,5.0,6.0,6.0,9.0
age,15915.0,1.394848,1.122193,0.0,0.0,1.0,2.0,3.0

In [11]:
df.describe(include=object).T

,count,unique,top,freq
make_model,15915,9,Audi A3,3097
body_type,15915,9,Sedans,7924
vat,15915,3,VAT deductible,10980
type,15915,5,Used,11096
inspection_new,15915,2,No,12345
body_color,15915,13,Black,3941
paint_type,15915,3,Metallic,15519
upholstery_texture,15915,6,Cloth,12460
upholstery_color,15915,10,Black,13110
gearing_type,15915,3,Manual,8149
fuel,15915,5,Gasoline,8542
emission_class,15915,3,Euro 6,15797
drive_chain,15915,3,Front,15707
country_version,15915,23,Germany,10725
entertainment_media,15915,346,"Bluetooth,Hands-free equipment,On-board comput...",1638
safety_security,15915,4442,"ABS,Central door lock,Daytime running lights,D...",729
comfort_convenience,15915,6197,"Air conditioning,Electrical side mirrors,Hill ...",315
extras,15915,659,Alloy wheels,5883

### Numerical columns

In [12]:
df_num = df.select_dtypes(include=np.number)
df_num.shape

(15915, 17)

### Categorical columns

In [13]:
df_cat = df.select_dtypes(exclude=np.number)
df_cat.head()
col_cat_multi = ['entertainment_media', 'safety_security', 'comfort_convenience', 'extras']
df_cat_bin = df_cat.drop(columns=col_cat_multi)
col_cat_bin = df_cat_bin.columns
df_cat_multi = df_cat[col_cat_multi]

#### OneHot encoding for single cell single class categorical columns

In [14]:
df_cat_bin_encode = pd.get_dummies(df_cat_bin, dtype=int, drop_first=True)

In [15]:
df_cat_bin_encode.head()

,make_model_Audi A2,make_model_Audi A3,make_model_Opel Astra,make_model_Opel Corsa,make_model_Opel Insignia,make_model_Renault Clio,make_model_Renault Duster,make_model_Renault Espace,body_type_Convertible,body_type_Coupe,body_type_Off-Road,body_type_Other,body_type_Sedans,body_type_Station wagon,body_type_Transporter,body_type_Van,vat_Price negotiable,vat_VAT deductible,type_Employee's car,type_New,type_Pre-registered,type_Used,inspection_new_Yes,body_color_Black,body_color_Blue,body_color_Bronze,body_color_Brown,body_color_Green,body_color_Grey,body_color_Orange,body_color_Red,body_color_Silver,body_color_Violet,body_color_White,body_color_Yellow,paint_type_Perl effect,paint_type_Uni/basic,upholstery_texture_Cloth,upholstery_texture_Full leather,upholstery_texture_Other,upholstery_texture_Part leather,upholstery_texture_Velour,upholstery_color_Black,upholstery_color_Blue,upholstery_color_Brown,upholstery_color_Grey,upholstery_color_Orange,upholstery_color_Other,upholstery_color_Red,upholstery_color_White,upholstery_color_Yellow,gearing_type_Manual,gearing_type_Semi-automatic,fuel_Electric,fuel_Gaseous,fuel_Gasoline,fuel_Others,emission_class_Euro 5,emission_class_Euro 6,drive_chain_Front,drive_chain_Rear,country_version_Belgium,country_version_Bulgaria,country_version_Croatia,country_version_Czech Republic,country_version_Denmark,country_version_Egypt,country_version_European Union,country_version_France,country_version_Germany,country_version_Hungary,country_version_Italy,country_version_Japan,country_version_Luxembourg,country_version_Netherlands,country_version_Poland,country_version_Romania,country_version_Serbia,country_version_Slovakia,country_version_Slovenia,country_version_Spain,country_version_Sweden,country_version_Switzerland
0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
df_cat_bin_encode.shape

(15915, 83)

#### OneHot encoding for single cell single multiple classes categorical columns

In [17]:
def ohe_multi(series):
    df_tmp = series.str.split(',').explode()
    df_tmp_ohe = pd.get_dummies(df_tmp, dtype=int)
    df_tmp_final = df_tmp_ohe.groupby(df_tmp.index).sum()
    return df_tmp_final

In [18]:
df_cat_multi_encode = pd.DataFrame(index=df_cat_multi.index)

for col in col_cat_multi:
    df_cat_multi_tmp = ohe_multi(df_cat_multi[col])
    df_cat_multi_encode = pd.concat([df_cat_multi_encode, df_cat_multi_tmp], axis=1)

In [19]:
df_cat_multi_encode.head()

,Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB,ABS,Adaptive Cruise Control,Adaptive headlights,Alarm system,Blind spot monitor,Central door lock,Central door lock with remote control,Daytime running lights,Driver drowsiness detection,Driver-side airbag,Electronic stability control,Emergency brake assistant,Emergency system,Fog lights,Head airbag,Immobilizer,Isofix,LED Daytime Running Lights,LED Headlights,Lane departure warning system,Night view assist,Passenger-side airbag,Power steering,Rear airbag,Side airbag,Tire pressure monitoring system,Traction control,Traffic sign recognition,Xenon headlights,Air conditioning,Air suspension,Armrest,Automatic climate control,Auxiliary heating,Cruise control,Electric Starter,Electric tailgate,Electrical side mirrors,Electrically adjustable seats,Electrically heated windshield,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather seats,Leather steering wheel,Light sensor,Lumbar support,Massage seats,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Seat ventilation,Split rear seats,Start-stop system,Sunroof,Tinted windows,Wind deflector,Windshield,Alloy wheels,Cab or rented Car,Catalytic Converter,Handicapped enabled,Right hand drive,Roof rack,Shift paddles,Ski bag,Sliding door,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Tuned car,Voice Control,Winter tyres
0,1,0,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,1,1,0,1,0,0,1,0,0,0,0,1,0,0,1,1,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1,0,0,1,0,1,1,1,0,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,1,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0
2,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,1,1,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,1,1,0,1,1,1,1,1,0,1,1,0,0,1,0,0,1,0,1,1,1,0,1,0,1,1,1,0,0,0,0,1,1,0,1,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,1,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,1,1,0,1,1,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,0,0,1,0,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0

In [20]:
df_cat_multi_encode.columns

Index(['Bluetooth', 'CD player', 'Digital radio', 'Hands-free equipment',
       'MP3', 'On-board computer', 'Radio', 'Sound system', 'Television',
       'USB', 'ABS', 'Adaptive Cruise Control', 'Adaptive headlights',
       'Alarm system', 'Blind spot monitor', 'Central door lock',
       'Central door lock with remote control', 'Daytime running lights',
       'Driver drowsiness detection', 'Driver-side airbag',
       'Electronic stability control', 'Emergency brake assistant',
       'Emergency system', 'Fog lights', 'Head airbag', 'Immobilizer',
       'Isofix', 'LED Daytime Running Lights', 'LED Headlights',
       'Lane departure warning system', 'Night view assist',
       'Passenger-side airbag', 'Power steering', 'Rear airbag', 'Side airbag',
       'Tire pressure monitoring system', 'Traction control',
       'Traffic sign recognition', 'Xenon headlights', 'Air conditioning',
       'Air suspension', 'Armrest', 'Automatic climate control',
       'Auxiliary heating', 'Cruise control', 'Electric Starter',
       'Electric tailgate', 'Electrical side mirrors',
       'Electrically adjustable seats', 'Electrically heated windshield',
       'Heads-up display', 'Heated steering wheel', 'Hill Holder',
       'Keyless central door lock', 'Leather seats', 'Leather steering wheel',
       'Light sensor', 'Lumbar support', 'Massage seats',
       'Multi-function steering wheel', 'Navigation system', 'Panorama roof',
       'Park Distance Control', 'Parking assist system camera',
       'Parking assist system self-steering',
       'Parking assist system sensors front',
       'Parking assist system sensors rear', 'Power windows', 'Rain sensor',
       'Seat heating', 'Seat ventilation', 'Split rear seats',
       'Start-stop system', 'Sunroof', 'Tinted windows', 'Wind deflector',
       'Windshield', 'Alloy wheels', 'Cab or rented Car',
       'Catalytic Converter', 'Handicapped enabled', 'Right hand drive',
       'Roof rack', 'Shift paddles', 'Ski bag', 'Sliding door',
       'Sport package', 'Sport seats', 'Sport suspension', 'Touch screen',
       'Trailer hitch', 'Tuned car', 'Voice Control', 'Winter tyres'],
      dtype='object')

In [21]:
df_cat_multi_encode.shape

(15915, 94)

### Dataset export

In [22]:
df_final = pd.concat([df_num, df_cat_bin_encode, df_cat_multi_encode], axis=1)

In [23]:
df_final.head()

,prev_owner,co2_emission,emission_label,consumption_comb,consumption_city,consumption_country,price,km,hp,displacement,warranty,weight,nr_of_doors,nr_of_seats,cylinders,gears,age,make_model_Audi A2,make_model_Audi A3,make_model_Opel Astra,make_model_Opel Corsa,make_model_Opel Insignia,make_model_Renault Clio,make_model_Renault Duster,make_model_Renault Espace,body_type_Convertible,body_type_Coupe,body_type_Off-Road,body_type_Other,body_type_Sedans,body_type_Station wagon,body_type_Transporter,body_type_Van,vat_Price negotiable,vat_VAT deductible,type_Employee's car,type_New,type_Pre-registered,type_Used,inspection_new_Yes,body_color_Black,body_color_Blue,body_color_Bronze,body_color_Brown,body_color_Green,body_color_Grey,body_color_Orange,body_color_Red,body_color_Silver,body_color_Violet,body_color_White,body_color_Yellow,paint_type_Perl effect,paint_type_Uni/basic,upholstery_texture_Cloth,upholstery_texture_Full leather,upholstery_texture_Other,upholstery_texture_Part leather,upholstery_texture_Velour,upholstery_color_Black,upholstery_color_Blue,upholstery_color_Brown,upholstery_color_Grey,upholstery_color_Orange,upholstery_color_Other,upholstery_color_Red,upholstery_color_White,upholstery_color_Yellow,gearing_type_Manual,gearing_type_Semi-automatic,fuel_Electric,fuel_Gaseous,fuel_Gasoline,fuel_Others,emission_class_Euro 5,emission_class_Euro 6,drive_chain_Front,drive_chain_Rear,country_version_Belgium,country_version_Bulgaria,country_version_Croatia,country_version_Czech Republic,country_version_Denmark,country_version_Egypt,country_version_European Union,country_version_France,country_version_Germany,country_version_Hungary,country_version_Italy,country_version_Japan,country_version_Luxembourg,country_version_Netherlands,country_version_Poland,country_version_Romania,country_version_Serbia,country_version_Slovakia,country_version_Slovenia,country_version_Spain,country_version_Sweden,country_version_Switzerland,Bluetooth,CD player,Digital radio,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB,ABS,Adaptive Cruise Control,Adaptive headlights,Alarm system,Blind spot monitor,Central door lock,Central door lock with remote control,Daytime running lights,Driver drowsiness detection,Driver-side airbag,Electronic stability control,Emergency brake assistant,Emergency system,Fog lights,Head airbag,Immobilizer,Isofix,LED Daytime Running Lights,LED Headlights,Lane departure warning system,Night view assist,Passenger-side airbag,Power steering,Rear airbag,Side airbag,Tire pressure monitoring system,Traction control,Traffic sign recognition,Xenon headlights,Air conditioning,Air suspension,Armrest,Automatic climate control,Auxiliary heating,Cruise control,Electric Starter,Electric tailgate,Electrical side mirrors,Electrically adjustable seats,Electrically heated windshield,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather seats,Leather steering wheel,Light sensor,Lumbar support,Massage seats,Multi-function steering wheel,Navigation system,Panorama roof,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Seat ventilation,Split rear seats,Start-stop system,Sunroof,Tinted windows,Wind deflector,Windshield,Alloy wheels,Cab or rented Car,Catalytic Converter,Handicapped enabled,Right hand drive,Roof rack,Shift paddles,Ski bag,Sliding door,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Tuned car,Voice Control,Winter tyres
0,2.0,99.0,4.0,3.8,4.3,3.5,15770,56013.0,66.0,1422.0,0.0,1220.0,5.0,5.0,3.0,5.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,1,1,0,1,0,0,1,0,0,0,0,1,0,0,1,1,0,0,1,1,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1.0,129.0,4.0,5.6,7.1,4.7,14500,80000.0,141.0,1798.0,0.0,1255.0,3.0,4.0,4.0,7.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,1,0,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,1,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0
2,1.0,99.0,4.0,3.8,4.4,3.4,14640,83450.0,85.0,1598.0,0.0,1195.0,4.0,4.0,3.0,5.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,1,1,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,1.0,99.0,4.0,3.8,4.3,3.5,14500,73000.0,66.0,1422.0,0.0,1195.0,3.0,4.0,3.0,6.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,1,0,1,1,0,0,1,0,0,1,0,1,1,1,0,1,0,1,1,1,0,0,0,0,1,1,0,1,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,1,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,1.0,109.0,4.0,4.1,4.6,3.8,16790,16200.0,66.0,1422.0,0.0,1195.0,5.0,5.0,3.0,5.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,0,0,1,0,1,1,0,0,0,0,1,1,0,1,1,1,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0

In [24]:
df_final.shape

(15915, 194)

In [25]:
df_final.columns = df_final.columns.str.lower().str.replace(' ', '_')

In [26]:
df_final.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15915 entries, 0 to 15914
Data columns (total 194 columns):
 #    Column                                 Dtype
---   ------                                 -----
 0    prev_owner                             float64
 1    co2_emission                           float64
 2    emission_label                         float64
 3    consumption_comb                       float64
 4    consumption_city                       float64
 5    consumption_country                    float64
 6    price                                  int64
 7    km                                     float64
 8    hp                                     float64
 9    displacement                           float64
 10   warranty                               float64
 11   weight                                 float64
 12   nr_of_doors                            float64
 13   nr_of_seats                            float64
 14   cylinders                              float64
 15   gears                                  float64
 16   age                                    float64
 17   make_model_audi_a2                     int64
 18   make_model_audi_a3                     int64
 19   make_model_opel_astra                  int64
 20   make_model_opel_corsa                  int64
 21   make_model_opel_insignia               int64
 22   make_model_renault_clio                int64
 23   make_model_renault_duster              int64
 24   make_model_renault_espace              int64
 25   body_type_convertible                  int64
 26   body_type_coupe                        int64
 27   body_type_off-road                     int64
 28   body_type_other                        int64
 29   body_type_sedans                       int64
 30   body_type_station_wagon                int64
 31   body_type_transporter                  int64
 32   body_type_van                          int64
 33   vat_price_negotiable                   int64
 34   vat_vat_deductible                     int64
 35   type_employee's_car                    int64
 36   type_new                               int64
 37   type_pre-registered                    int64
 38   type_used                              int64
 39   inspection_new_yes                     int64
 40   body_color_black                       int64
 41   body_color_blue                        int64
 42   body_color_bronze                      int64
 43   body_color_brown                       int64
 44   body_color_green                       int64
 45   body_color_grey                        int64
 46   body_color_orange                      int64
 47   body_color_red                         int64
 48   body_color_silver                      int64
 49   body_color_violet                      int64
 50   body_color_white                       int64
 51   body_color_yellow                      int64
 52   paint_type_perl_effect                 int64
 53   paint_type_uni/basic                   int64
 54   upholstery_texture_cloth               int64
 55   upholstery_texture_full_leather        int64
 56   upholstery_texture_other               int64
 57   upholstery_texture_part_leather        int64
 58   upholstery_texture_velour              int64
 59   upholstery_color_black                 int64
 60   upholstery_color_blue                  int64
 61   upholstery_color_brown                 int64
 62   upholstery_color_grey                  int64
 63   upholstery_color_orange                int64
 64   upholstery_color_other                 int64
 65   upholstery_color_red                   int64
 66   upholstery_color_white                 int64
 67   upholstery_color_yellow                int64
 68   gearing_type_manual                    int64
 69   gearing_type_semi-automatic            int64
 70   fuel_electric                          int64
 71   fuel_gaseous                           int64
 72   fuel_gasoline                          int64
 73   fuel_others                            int64
 74   emission_class_euro_5                  int64
 75   emission_class_euro_6                  int64
 76   drive_chain_front                      int64
 77   drive_chain_rear                       int64
 78   country_version_belgium                int64
 79   country_version_bulgaria               int64
 80   country_version_croatia                int64
 81   country_version_czech_republic         int64
 82   country_version_denmark                int64
 83   country_version_egypt                  int64
 84   country_version_european_union         int64
 85   country_version_france                 int64
 86   country_version_germany                int64
 87   country_version_hungary                int64
 88   country_version_italy                  int64
 89   country_version_japan                  int64
 90   country_version_luxembourg             int64
 91   country_version_netherlands            int64
 92   country_version_poland                 int64
 93   country_version_romania                int64
 94   country_version_serbia                 int64
 95   country_version_slovakia               int64
 96   country_version_slovenia               int64
 97   country_version_spain                  int64
 98   country_version_sweden                 int64
 99   country_version_switzerland            int64
 100  bluetooth                              int64
 101  cd_player                              int64
 102  digital_radio                          int64
 103  hands-free_equipment                   int64
 104  mp3                                    int64
 105  on-board_computer                      int64
 106  radio                                  int64
 107  sound_system                           int64
 108  television                             int64
 109  usb                                    int64
 110  abs                                    int64
 111  adaptive_cruise_control                int64
 112  adaptive_headlights                    int64
 113  alarm_system                           int64
 114  blind_spot_monitor                     int64
 115  central_door_lock                      int64
 116  central_door_lock_with_remote_control  int64
 117  daytime_running_lights                 int64
 118  driver_drowsiness_detection            int64
 119  driver-side_airbag                     int64
 120  electronic_stability_control           int64
 121  emergency_brake_assistant              int64
 122  emergency_system                       int64
 123  fog_lights                             int64
 124  head_airbag                            int64
 125  immobilizer                            int64
 126  isofix                                 int64
 127  led_daytime_running_lights             int64
 128  led_headlights                         int64
 129  lane_departure_warning_system          int64
 130  night_view_assist                      int64
 131  passenger-side_airbag                  int64
 132  power_steering                         int64
 133  rear_airbag                            int64
 134  side_airbag                            int64
 135  tire_pressure_monitoring_system        int64
 136  traction_control                       int64
 137  traffic_sign_recognition               int64
 138  xenon_headlights                       int64
 139  air_conditioning                       int64
 140  air_suspension                         int64
 141  armrest                                int64
 142  automatic_climate_control              int64
 143  auxiliary_heating                      int64
 144  cruise_control                         int64
 145  electric_starter                       int64
 146  electric_tailgate                      int64
 147  electrical_side_mirrors                int64
 148  electrically_adjustable_seats          int64
 149  electrically_heated_windshield         int64
 150  heads-up_display                       int64
 151  heated_steering_wheel                  int64
 152  hill_holder                            int64
 153  keyless_central_door_lock              int64
 154  leather_seats                          int64
 155  leather_steering_wheel                 int64
 156  light_sensor                           int64
 157  lumbar_support                         int64
 158  massage_seats                          int64
 159  multi-function_steering_wheel          int64
 160  navigation_system                      int64
 161  panorama_roof                          int64
 162  park_distance_control                  int64
 163  parking_assist_system_camera           int64
 164  parking_assist_system_self-steering    int64
 165  parking_assist_system_sensors_front    int64
 166  parking_assist_system_sensors_rear     int64
 167  power_windows                          int64
 168  rain_sensor                            int64
 169  seat_heating                           int64
 170  seat_ventilation                       int64
 171  split_rear_seats                       int64
 172  start-stop_system                      int64
 173  sunroof                                int64
 174  tinted_windows                         int64
 175  wind_deflector                         int64
 176  windshield                             int64
 177  alloy_wheels                           int64
 178  cab_or_rented_car                      int64
 179  catalytic_converter                    int64
 180  handicapped_enabled                    int64
 181  right_hand_drive                       int64
 182  roof_rack                              int64
 183  shift_paddles                          int64
 184  ski_bag                                int64
 185  sliding_door                           int64
 186  sport_package                          int64
 187  sport_seats                            int64
 188  sport_suspension                       int64
 189  touch_screen                           int64
 190  trailer_hitch                          int64
 191  tuned_car                              int64
 192  voice_control                          int64
 193  winter_tyres                           int64
dtypes: float64(16), int64(178)
memory usage: 23.6 MB

In [27]:
df_final.to_csv(drive_data_dir+'/data_final.csv', index=False)